In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Example 1

In [2]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print("X:-\n")
for i in range(len(X)):
    print(X[i])
print("\nAfter filling nan values :-\n",imp_mean.transform(X))


X:-

[nan, 2, 3]
[4, nan, 6]
[10, nan, 9]

After filling nan values :-
 [[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


# Example 2

In [3]:
smplimputr = SimpleImputer(strategy="most_frequent")
array = np.array([[1,2,3,5],[5,2,np.nan,4],[8,5,np.nan,7],[5,4,np.nan,np.nan]])
print(array)
smplimputr.fit(array)
smplimputr.transform(array)

[[ 1.  2.  3.  5.]
 [ 5.  2. nan  4.]
 [ 8.  5. nan  7.]
 [ 5.  4. nan nan]]


array([[1., 2., 3., 5.],
       [5., 2., 3., 4.],
       [8., 5., 3., 7.],
       [5., 4., 3., 4.]])

# Example 3

In [4]:
smplimputr = SimpleImputer(strategy="constant",fill_value=19)
array = np.array([[1,2,3,5],[5,2,np.nan,4],[8,5,np.nan,7],[5,4,np.nan,np.nan]])
print(array)
smplimputr.fit(array)
smplimputr.transform(array)

[[ 1.  2.  3.  5.]
 [ 5.  2. nan  4.]
 [ 8.  5. nan  7.]
 [ 5.  4. nan nan]]


array([[ 1.,  2.,  3.,  5.],
       [ 5.,  2., 19.,  4.],
       [ 8.,  5., 19.,  7.],
       [ 5.,  4., 19., 19.]])

# Example 4

In [5]:
smplimputr = SimpleImputer(strategy="median")
array = np.array([[1,2,3,5],[5,2,np.nan,4],[8,5,7,7],[5,4,9,np.nan]])
print(array)
smplimputr.fit(array)
smplimputr.transform(array)

[[ 1.  2.  3.  5.]
 [ 5.  2. nan  4.]
 [ 8.  5.  7.  7.]
 [ 5.  4.  9. nan]]


array([[1., 2., 3., 5.],
       [5., 2., 7., 4.],
       [8., 5., 7., 7.],
       [5., 4., 9., 5.]])

# Now we'll fill values into DataFrame

In [6]:
df = pd.read_csv("FillValues.csv")
df.head(7)

Year  Exp
0  2000.0  3.0
1  2050.0  5.0
2  2030.0  1.0
3  2010.0  2.0
4     NaN  NaN
5  2020.0  NaN

In [7]:
# Filling Year column value
fill = SimpleImputer(strategy='mean')
fill.fit(np.array(df['Year']).reshape(-1,1))
df.Year = fill.transform(np.array(df['Year']).reshape(-1,1))

In [8]:
#To get the mean value
fill.fit(np.array(df['Year']).reshape(-1,1)).statistics_

array([2022.])

In [9]:
df.Year 

0    2000.0
1    2050.0
2    2030.0
3    2010.0
4    2022.0
5    2020.0
Name: Year, dtype: float64

In [10]:
sum([2000,2050,2010,2020,2030])/len([2000,2050,2030,2010,2020])

2022.0

In [11]:
df.Exp

0    3.0
1    5.0
2    1.0
3    2.0
4    NaN
5    NaN
Name: Exp, dtype: float64

In [12]:
# Filling Exp column value
fill = SimpleImputer(strategy='mean')
fill.fit(np.array(df['Exp']).reshape(-1,1))
df.Exp = fill.transform(np.array(df['Exp']).reshape(-1,1))

In [13]:
#To get the mean value of df.Exp
fill.fit(np.array(df['Exp']).reshape(-1,1)).statistics_

array([2.75])

In [14]:
df.Exp

0    3.00
1    5.00
2    1.00
3    2.00
4    2.75
5    2.75
Name: Exp, dtype: float64

## How we hv filled none values

In [15]:
df.head(10)

Year   Exp
0  2000.0  3.00
1  2050.0  5.00
2  2030.0  1.00
3  2010.0  2.00
4  2022.0  2.75
5  2020.0  2.75