In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
kol = pd.read_csv("C://Users//idofa//Projects//House Price Prediction//DataSets//Kolkata.csv")
kol.head()

Price  Area     Location  No. of Bedrooms  Resale  MaintenanceStaff  \
0  2235000  1016      Barasat                3       0                 0   
1  3665999  1111    Keshtopur                2       0                 1   
2  3774000  1020     Rajarhat                2       0                 0   
3  2524000   935  Narendrapur                2       0                 0   
4  8300000  1956     New Town                3       1                 0   

   Gymnasium  SwimmingPool  LandscapedGardens  JoggingTrack  ...  \
0          1             1                  1             1  ...   
1          1             0                  1             1  ...   
2          1             0                  0             0  ...   
3          1             1                  1             1  ...   
4          1             1                  1             1  ...   

   LiftAvailable  BED  VaastuCompliant  Microwave  GolfCourse  TV  \
0              1    0                0          0           0   0   
1              0    0                0          0           0   0   
2              1    0                0          0           0   0   
3              0    0                0          0           0   0   
4              1    0                1          0           0   0   

   DiningTable  Sofa  Wardrobe  Refrigerator  
0            0     0         0             0  
1            0     0         0             0  
2            0     0         0             0  
3            0     0         0             0  
4            0     0         0             0  

[5 rows x 40 columns]

In [4]:
kol = kol[["Area","Price"]]
kol.head()

Area    Price
0  1016  2235000
1  1111  3665999
2  1020  3774000
3   935  2524000
4  1956  8300000

In [6]:
model = LinearRegression()
model.fit(kol[['Area']] , kol[['Price']])

LinearRegression()

In [7]:
model.coef_

array([[4226.83148651]])

In [8]:
model.intercept_

array([2827002.70357863])

In [9]:
model.predict([[1016]])

array([[7121463.49387779]])

In [10]:
model.score(kol[['Area']],kol[["Price"]])

0.05423706157753572

## Save Model To a File Using Python Pickle

In [1]:
import pickle

In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

##### Load Saved Model

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([[4226.83148651]])

In [14]:
mp.intercept_

array([2827002.70357863])

In [15]:
mp.predict([[5000]])

array([[23961160.13615325]])

##### Save Trained Model Using joblib

In [19]:
pip install joblib

In [22]:
import joblib

In [23]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [24]:
m_J = joblib.load('model_joblib')

In [ ]:
m_J

In [17]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\idofa\anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [18]:
!pip install sklearn.externals

ERROR: Could not find a version that satisfies the requirement sklearn.externals (from versions: none)
ERROR: No matching distribution found for sklearn.externals
