In [4]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
#from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_score

In [5]:
dta =sm.datasets.fair.load_pandas().data
#add "affair" column: 1 represents having affairs, 0 represents not 
dta['affair'] = (dta.affairs >0).astype(int)


In [32]:
dta.drop(["affairs"],axis=1,inplace = True)

In [33]:
dta.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb  affair  
0              5.0       1  
1              4.0       1  
2              5.0       1  
3              5.0       1  
4              4.0       1

In [34]:
dta.shape

(6366, 9)

In [35]:
dta.describe()

rate_marriage          age  yrs_married     children    religious  \
count    6366.000000  6366.000000  6366.000000  6366.000000  6366.000000   
mean        4.109645    29.082862     9.009425     1.396874     2.426170   
std         0.961430     6.847882     7.280120     1.433471     0.878369   
min         1.000000    17.500000     0.500000     0.000000     1.000000   
25%         4.000000    22.000000     2.500000     0.000000     2.000000   
50%         4.000000    27.000000     6.000000     1.000000     2.000000   
75%         5.000000    32.000000    16.500000     2.000000     3.000000   
max         5.000000    42.000000    23.000000     5.500000     4.000000   

              educ   occupation  occupation_husb       affair  
count  6366.000000  6366.000000      6366.000000  6366.000000  
mean     14.209865     3.424128         3.850141     0.322495  
std       2.178003     0.942399         1.346435     0.467468  
min       9.000000     1.000000         1.000000     0.000000  
25%      12.000000     3.000000         3.000000     0.000000  
50%      14.000000     3.000000         4.000000     0.000000  
75%      16.000000     4.000000         5.000000     1.000000  
max      20.000000     6.000000         6.000000     1.000000

In [36]:
#Checking whether there is any null value or not
dta.isnull().sum()

rate_marriage      0
age                0
yrs_married        0
children           0
religious          0
educ               0
occupation         0
occupation_husb    0
affair             0
dtype: int64

In [37]:
#Checking types of each data column
print("ColumnName\tDatatype\n",'-'*25)

for i in dta.columns:
    print(i,'\t', dta[i].dtype)

ColumnName	Datatype
 -------------------------
rate_marriage 	 float64
age 	 float64
yrs_married 	 float64
children 	 float64
religious 	 float64
educ 	 float64
occupation 	 float64
occupation_husb 	 float64
affair 	 int32


In [38]:
dta["rate_marriage"].dtype

dtype('float64')

In [41]:
print("ColumnName\tUnique_Values\n",'-'*30)
for i in dta.columns:
    print(i,'\t',dta[i].unique())

ColumnName	Unique_Values
 ------------------------------
rate_marriage 	 [3. 4. 5. 2. 1.]
age 	 [32.  27.  22.  37.  42.  17.5]
yrs_married 	 [ 9.  13.   2.5 16.5 23.   6.   0.5]
children 	 [3.  0.  4.  1.  5.5 2. ]
religious 	 [3. 1. 2. 4.]
educ 	 [17. 14. 16. 12. 20.  9.]
occupation 	 [2. 3. 5. 4. 1. 6.]
occupation_husb 	 [5. 4. 3. 2. 6. 1.]
affair 	 [1 0]


In [17]:
dta.children.unique()

array([3. , 0. , 4. , 1. , 5.5, 2. ])

In [43]:
dta.iloc[:,0:8]

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb  
0                 5.0  
1                 4.0  
2                 5.0  
3                 5.0  
4                 4.0  
...               ...  
6361              3.0  
6362              5.0  
6363              1.0  
6364              4.0  
6365              4.0  

[6366 rows x 8 columns]

In [44]:
x_train , x_test , y_train , y_test = train_test_split(dta.iloc[:,0:8],dta.iloc[:,-1])

In [45]:
for i in [x_train , x_test , y_train , y_test ]:
    print(i.shape)

(4774, 8)
(1592, 8)
(4774,)
(1592,)


In [46]:
model = LogisticRegression()
model.fit(x_train , y_train)

LogisticRegression()

In [47]:
y_pred = model.predict(x_test)

In [48]:
y_pred

array([1, 0, 0, ..., 0, 1, 1])

In [55]:
np.array(y_test).reshape(1,-1)

array([[1, 0, 1, ..., 0, 1, 1]])

In [58]:
np.ravel(y_test).ndim

1

In [59]:
np.ravel(y_test)

array([1, 0, 1, ..., 0, 1, 1])